<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<style type="text/css">
.ansi2html-content { display: inline; white-space: pre-wrap; word-wrap: break-word; }
.body_foreground { color: #AAAAAA; }
.body_background { background-color: #000000; }
.body_foreground > .bold,.bold > .body_foreground, body.body_foreground > pre > .bold { color: #FFFFFF; font-weight: normal; }
.inv_foreground { color: #000000; }
.inv_background { background-color: #AAAAAA; }
</style>
</head>
<body class="body_foreground body_background" style="font-size: normal;" >
<pre class="ansi2html-content">
2019-08-05 10:57:50 default CRITICAL cinder [-] Unhandled error: VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: You must install hpe3parclient before using 3PAR drivers. Run "pip install python-3parclient" to install the hpe3parclient.
2019-08-05 10:57:50.196 1 ERROR cinder Traceback (most recent call last):
2019-08-05 10:57:50.196 1 ERROR cinder   File "/usr/bin/ember-csi", line 9, in &lt;module&gt;
2019-08-05 10:57:50.196 1 ERROR cinder     load_entry_point('ember-csi==0.9.0', 'console_scripts', 'ember-csi')()
2019-08-05 10:57:50.196 1 ERROR cinder   File "/ember-csi/ember_csi/ember_csi.py", line 52, in main
2019-08-05 10:57:50.196 1 ERROR cinder     node_id=node_id)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/ember-csi/ember_csi/v1_0_0/csi.py", line 255, in __init__
2019-08-05 10:57:50.196 1 ERROR cinder     ember_config=ember_config)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/ember-csi/ember_csi/v1_0_0/csi.py", line 54, in __init__
2019-08-05 10:57:50.196 1 ERROR cinder     **kwargs)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/ember-csi/ember_csi/base.py", line 234, in __init__
2019-08-05 10:57:50.196 1 ERROR cinder     self.backend = cinderlib.Backend(**backend_config)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinderlib/cinderlib.py", line 87, in __init__
2019-08-05 10:57:50.196 1 ERROR cinder     self.driver.do_setup(objects.CONTEXT)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_base.py", line 435, in do_setup
2019-08-05 10:57:50.196 1 ERROR cinder     common.do_setup(context)
2019-08-05 10:57:50.196 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py", line 466, in do_setup
2019-08-05 10:57:50.196 1 ERROR cinder     raise exception.VolumeBackendAPIException(data=msg)
2019-08-05 10:57:50.196 1 ERROR cinder VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: You must install hpe3parclient before using 3PAR drivers. Run "pip install python-3parclient" to install the hpe3parclient.
2019-08-05 10:57:50.196 1 ERROR cinder 
Exception AttributeError: "'NoneType' object has no attribute 'getcurrent'" in &lt;function _removeHandlerRef at 0x7fc0c06ef848&gt; ignored

</pre>
</body>

</html>
